version: '3.8'

services:
  frontend:
    build:
      context: ./orbit-marketplace/dashboard-web-app
      dockerfile: Dockerfile
    container_name: orbit-frontend
    restart: always
    ports:
      - '127.0.0.1:3000:3000'
    env_file:
      - .env.production
    depends_on:
      - backend

  backend:
    build:
      context: ./orbit-marketplace/backend
      dockerfile: Dockerfile
    container_name: orbit-backend
    restart: always
    ports:
      - '127.0.0.1:5000:5000'
      - '127.0.0.1:3003:3003'
    env_file:
      - .env.production
