import { useEffect, useMemo, useState } from 'react'
import { Camera, Check, ChevronRight, Clock, Download, Film, LayoutDashboard, MapPin, Upload, User, Wallet, X } from 'lucide-react'
import { useStore } from './lib/store'
import { STATUS_COLORS, STATUS_FLOW, STATUS_LABELS, type Booking, type Editor, type Partner, type Role } from './lib/types'

const roleInfo: Record<Exclude<Role, 'none'>, { title: string; description: string; icon: typeof User; color: string }> = {
  client: { title: 'Client', description: 'Book a session and download your finished reel.', icon: User, color: 'from-blue-500 to-cyan-500' },
  partner: { title: 'Partner', description: 'Accept shoots, capture footage, and earn ₹700 per order.', icon: Camera, color: 'from-emerald-500 to-teal-500' },
  editor: { title: 'Editor', description: 'Accept uploaded footage and deliver the final reel.', icon: Film, color: 'from-fuchsia-500 to-pink-500' },
  admin: { title: 'Admin', description: 'Monitor the complete pipeline, history, and payouts.', icon: LayoutDashboard, color: 'from-amber-500 to-orange-500' },
}

export default function App() {
  const role = useStore((s) => s.role)
  const [ready, setReady] = useState(false)
  const initialise = async () => {
    await Promise.all([
      useStore.getState().fetchPackages(), useStore.getState().fetchPartners(),
      useStore.getState().fetchEditors(), useStore.getState().fetchBookings(), useStore.getState().fetchEarnings(),
    ])
    setReady(true)
  }
  useEffect(() => {
    initialise()
    return useStore.getState().subscribeToBookings()
  }, [])
  if (!ready) return <div className="loading"><div className="spinner" /><span>Orbit is loading</span></div>
  if (role === 'none') return <RolePicker />
  return <RoleShell role={role} />
}

function RolePicker() {
  const setRole = useStore((s) => s.setRole)
  return <main className="picker page-shell"><div className="hero-glow" /><div className="brand-mark">O</div><p className="eyebrow">REAL-TIME CREATIVE DELIVERY</p><h1>Book. Shoot. <span>Edit.</span> Deliver.</h1><p className="lead">One connected workflow for cinematic content, from the first request to the final download.</p><div className="role-grid">{(Object.keys(roleInfo) as Exclude<Role, 'none'>[]).map((role) => { const item = roleInfo[role]; const Icon = item.icon; return <button className="role-card" key={role} onClick={() => setRole(role)}><div className={`role-icon ${item.color}`}><Icon size={22} /></div><div><strong>{item.title}</strong><p>{item.description}</p></div><ChevronRight className="role-arrow" size={18} /></button> })}</div></main>
}

function RoleShell({ role }: { role: Exclude<Role, 'none'> }) {
  const setRole = useStore((s) => s.setRole)
  const item = roleInfo[role]
  const Icon = item.icon
  return <div className="app-shell"><header className="topbar"><div className="brand-small"><span>O</span><div><strong>ORBIT</strong><small>{item.title} workspace</small></div></div><div className="topbar-actions"><span className="live-dot">Live sync</span><button className="switch" onClick={() => setRole('none')}>Switch role</button></div></header><main className="content"><div className="section-heading"><div><p className="eyebrow">{role.toUpperCase()} WORKSPACE</p><h2>{role === 'client' ? 'Your content, in motion.' : role === 'partner' ? 'Capture what matters.' : role === 'editor' ? 'Shape the final story.' : 'The whole operation, at a glance.'}</h2></div><div className={`role-icon ${item.color}`}><Icon size={21} /></div></div>{role === 'client' && <ClientView />}{role === 'partner' && <PartnerView />}{role === 'editor' && <EditorView />}{role === 'admin' && <AdminView />}</main></div>
}

function ClientView() {
  const packages = useStore((s) => s.packages); const bookings = useStore((s) => s.bookings); const partners = useStore((s) => s.partners); const createBooking = useStore((s) => s.createBooking); const cancelBooking = useStore((s) => s.cancelBooking)
  const [tab, setTab] = useState<'book' | 'track' | 'history'>('book'); const [pkgId, setPkgId] = useState(''); const [form, setForm] = useState({ name: '', phone: '', date: '', slot: '', location: '', notes: '' }); const [busy, setBusy] = useState(false)
  const active = bookings.find((b) => !['DELIVERED', 'CANCELLED'].includes(b.status)); const completed = bookings.filter((b) => b.status === 'DELIVERED')
  const set = (key: keyof typeof form, value: string) => setForm((old) => ({ ...old, [key]: value }))
  const submit = async () => { const pkg = packages.find((p) => p.id === pkgId); if (!pkg || !form.name || !form.phone) return; setBusy(true); await createBooking({ client_name: form.name, client_phone: form.phone, package_id: pkg.id, package_name: pkg.name, package_price: pkg.price, status: 'PENDING', booking_date: form.date || null, time_slot: form.slot || null, location: form.location || null, notes: form.notes || null }); setBusy(false); setTab('track') }
  return <><Nav tabs={[['book', 'Book session'], ['track', `Track ${active ? '· 1 active' : ''}`], ['history', `History · ${completed.length}`]]} active={tab} setActive={setTab} />{tab === 'book' && <div className="two-col"><div className="stack"><div className="panel"><p className="eyebrow">01 / CHOOSE A PACKAGE</p><h3>Made for your moment</h3><div className="package-list">{packages.map((pkg) => <button className={`package-card ${pkgId === pkg.id ? 'selected' : ''}`} key={pkg.id} onClick={() => setPkgId(pkg.id)}><div><strong>{pkg.name}</strong><p>{pkg.description}</p><small>{pkg.delivery_time} · {pkg.features.slice(0, 2).join(' · ')}</small></div><b>₹{pkg.price.toLocaleString()}</b></button>)}</div></div></div><div className="panel form-panel"><p className="eyebrow">02 / SESSION DETAILS</p><h3>Tell us where to meet</h3><Field label="Name *" value={form.name} onChange={(v) => set('name', v)} placeholder="Your name" /><Field label="Phone *" value={form.phone} onChange={(v) => set('phone', v)} placeholder="+91 98765 43210" /><div className="form-row"><Field label="Date" type="date" value={form.date} onChange={(v) => set('date', v)} /><select className="input" value={form.slot} onChange={(e) => set('slot', e.target.value)}><option value="">Time slot</option><option>Morning · 9–11 AM</option><option>Afternoon · 12–2 PM</option><option>Evening · 4–6 PM</option></select></div><Field label="Location" value={form.location} onChange={(v) => set('location', v)} placeholder="Mumbai, India" /><Field label="Notes" value={form.notes} onChange={(v) => set('notes', v)} placeholder="Anything our team should know?" /><button className="primary full" disabled={busy || !pkgId || !form.name || !form.phone} onClick={submit}>{busy ? 'Creating booking…' : 'Request a session'} <ChevronRight size={17} /></button><p className="helper">Your request goes to a partner first. Nothing starts until they accept.</p></div></div>}{tab === 'track' && <ClientTracking active={active} cancelBooking={cancelBooking} />}{tab === 'history' && <div className="list">{completed.length ? completed.map((b) => <BookingRow key={b.id} booking={b} />) : <Empty icon={Film} text="Your completed sessions will appear here." />}</div>}</>
}

function ClientTracking({ active, cancelBooking }: { active?: Booking; cancelBooking: (id: string) => Promise<void> }) { if (!active) return <Empty icon={Clock} text="No active session. Start with a new booking." />; const index = STATUS_FLOW.indexOf(active.status); return <div className="tracking-wrap"><div className="panel tracking-card"><div className="row-between"><div><p className="eyebrow">ACTIVE SESSION</p><h3>{active.package_name}</h3><p className="muted">{active.client_name} · ₹{active.package_price.toLocaleString()}</p></div><Status status={active.status} /></div><div className="timeline">{STATUS_FLOW.map((status, i) => <div className={`timeline-item ${i <= index ? 'done' : ''} ${i === index ? 'current' : ''}`} key={status}><div className="timeline-dot">{i <= index ? <Check size={13} /> : i + 1}</div><span>{STATUS_LABELS[status]}</span></div>)}</div>{active.reel_url && <a className="success full" href={active.reel_url} download><Download size={17} /> Download your reel</a>}{active.status === 'PENDING' && <button className="danger full" onClick={() => cancelBooking(active.id)}><X size={17} /> Cancel request</button>}</div></div> }

function PartnerView() { const bookings = useStore((s) => s.bookings); const partners = useStore((s) => s.partners); const earnings = useStore((s) => s.earnings); const accept = useStore((s) => s.acceptBookingByPartner); const update = useStore((s) => s.updateBookingStatus); const upload = useStore((s) => s.uploadFootage); const me = partners[0]; const [url, setUrl] = useState(''); const incoming = bookings.filter((b) => b.status === 'PENDING'); const mine = bookings.filter((b) => b.partner_id === me?.id && !['DELIVERED', 'CANCELLED'].includes(b.status)); const total = earnings.filter((e) => e.partner_id === me?.id).reduce((n, e) => n + e.amount, 0); return <><div className="metric-grid"><Metric label="Total earned" value={`₹${total}`} icon={Wallet} /><Metric label="Per order" value="₹700" icon={Check} /><Metric label="Completed jobs" value={me?.completed_jobs || 0} icon={Camera} /></div><div className="two-col"><div className="panel"><div className="row-between"><div><p className="eyebrow">INCOMING REQUESTS</p><h3>{incoming.length ? `${incoming.length} session${incoming.length > 1 ? 's' : ''} waiting` : 'All caught up'}</h3></div><span className="live-dot">Live</span></div><div className="list">{incoming.map((b) => <div className="job-card" key={b.id}><div className="row-between"><div><strong>{b.package_name}</strong><p className="muted">{b.client_name}</p></div><b className="green">₹700</b></div><p className="muted small"><Clock size={13} /> {b.booking_date || 'Flexible'} · <MapPin size={13} /> {b.location || 'To be confirmed'}</p><div className="actions"><button className="success" onClick={() => me && accept(b.id, me)}><Check size={16} /> Accept shoot</button></div></div>)}{!incoming.length && <Empty icon={Camera} text="New client requests will appear here." />}</div></div><div className="panel"><p className="eyebrow">MY ACTIVE WORK</p><h3>Capture and upload</h3><div className="list">{mine.map((b) => <div className="job-card" key={b.id}><div className="row-between"><div><strong>{b.package_name}</strong><p className="muted">{b.client_name}</p></div><Status status={b.status} /></div>{b.status === 'ACCEPTED_BY_PARTNER' && <button className="primary" onClick={() => update(b.id, 'SHOOTING')}><Camera size={16} /> Start shooting</button>}{b.status === 'SHOOTING' && <><input className="input" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="Paste footage link" /><button className="success" disabled={!url} onClick={() => upload(b.id, url)}><Upload size={16} /> Send to editor</button></>}{b.status === 'UPLOADED' && <p className="helper green"><Check size={14} /> Uploaded. Waiting for editor acceptance.</p>}</div>)}{!mine.length && <Empty icon={Film} text="Accept a request to see it here." />}</div></div></div></> }

function EditorView() { const bookings = useStore((s) => s.bookings); const editors = useStore((s) => s.editors); const accept = useStore((s) => s.acceptBookingByEditor); const deliver = useStore((s) => s.deliverReel); const me = editors[0]; const queue = bookings.filter((b) => b.status === 'UPLOADED'); const mine = bookings.filter((b) => b.editor_id === me?.id && b.status === 'EDITING'); const [url, setUrl] = useState(''); return <><div className="metric-grid"><Metric label="Ready in queue" value={queue.length} icon={Film} /><Metric label="Active edits" value={mine.length} icon={Clock} /><Metric label="Editor rating" value={`★ ${me?.rating || '—'}`} icon={Check} /></div><div className="two-col"><div className="panel"><p className="eyebrow">EDITING QUEUE</p><h3>Footage ready for your eye</h3><div className="list">{queue.map((b) => <div className="job-card" key={b.id}><div className="row-between"><div><strong>{b.package_name}</strong><p className="muted">{b.client_name} · {b.partner_name}</p></div><Status status={b.status} /></div>{b.raw_footage_url && <a className="link-button" href={b.raw_footage_url} target="_blank" rel="noreferrer">Preview footage <ChevronRight size={15} /></a>}<button className="primary" onClick={() => me && accept(b.id, me)}><Check size={16} /> Accept & start editing</button></div>)}{!queue.length && <Empty icon={Film} text="The queue is clear. Waiting for partner uploads." />}</div></div><div className="panel"><p className="eyebrow">ACTIVE EDITS</p><h3>Deliver when it shines</h3><div className="list">{mine.map((b) => <div className="job-card" key={b.id}><div className="row-between"><div><strong>{b.package_name}</strong><p className="muted">{b.client_name}</p></div><Status status={b.status} /></div><input className="input" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="Paste final reel link" /><button className="success" disabled={!url} onClick={() => deliver(b.id, url)}><Upload size={16} /> Deliver to client</button></div>)}{!mine.length && <Empty icon={Clock} text="Accept a queue item to begin editing." />}</div></div></div></> }

function AdminView() { const bookings = useStore((s) => s.bookings); const partners = useStore((s) => s.partners); const editors = useStore((s) => s.editors); const earnings = useStore((s) => s.earnings); const delivered = bookings.filter((b) => b.status === 'DELIVERED'); const revenue = delivered.reduce((n, b) => n + b.package_price, 0); return <><div className="metric-grid"><Metric label="Total bookings" value={bookings.length} icon={LayoutDashboard} /><Metric label="Revenue" value={`₹${revenue.toLocaleString()}`} icon={Wallet} /><Metric label="Partner payouts" value={`₹${earnings.reduce((n, e) => n + e.amount, 0).toLocaleString()}`} icon={Check} /><Metric label="Delivered" value={delivered.length} icon={Download} /></div><div className="panel"><div className="row-between"><div><p className="eyebrow">BOOKING HISTORY</p><h3>Every request, one view</h3></div><span className="muted">{partners.length} partners · {editors.length} editors</span></div><div className="table-list">{bookings.length ? bookings.map((b) => <BookingRow key={b.id} booking={b} />) : <Empty icon={LayoutDashboard} text="Bookings will appear as clients request sessions." />}</div></div></> }

function Nav({ tabs, active, setActive }: { tabs: [string, string][]; active: string; setActive: (x: any) => void }) { return <div className="tabs">{tabs.map(([id, label]) => <button className={active === id ? 'active' : ''} key={id} onClick={() => setActive(id)}>{label}</button>)}</div> }
function Field({ label, value, onChange, placeholder, type = 'text' }: { label: string; value: string; onChange: (v: string) => void; placeholder?: string; type?: string }) { return <label className="field"><span>{label}</span><input className="input" type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} /></label> }
function Status({ status }: { status: Booking['status'] }) { return <span className={`status ${STATUS_COLORS[status]}`}>{STATUS_LABELS[status]}</span> }
function BookingRow({ booking: b }: { booking: Booking }) { return <div className="booking-row"><div><strong>{b.client_name}</strong><p className="muted">{b.package_name} · {b.partner_name || 'Partner pending'} · {b.editor_name || 'Editor pending'}</p></div><div className="row-right"><Status status={b.status} /><b>₹{b.package_price.toLocaleString()}</b></div></div> }
function Metric({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof Check }) { return <div className="metric"><Icon size={18} /><strong>{value}</strong><span>{label}</span></div> }
function Empty({ icon: Icon, text }: { icon: typeof Check; text: string }) { return <div className="empty"><Icon size={28} /><p>{text}</p></div> }
